2024-12-10 10:03:32,636 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-10 10:03:32,636 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Configure stats pid to 3555708
2024-12-10 10:03:32,636 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Loading settings from /home/pkr/.config/wandb/settings
2024-12-10 10:03:32,636 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Loading settings from /mnt/DGX01/Personal/krusepi/codebase/projects/llms/JAIL-RAG/notebooks/wandb/settings
2024-12-10 10:03:32,636 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-10 10:03:32,636 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-10 10:03:32,658 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-12-10 10:03:32,658 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-10 10:03:32,658 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-10 10:03:32,658 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-12-10 10:03:32,659 ERROR   MainThread:3555708 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3555708/1765679085.py", line 3, in <module>
    wandb.init(project=f"{args.project}",
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/analytics/sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 304, in setup
    wandb_login._login(
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 274, in prompt_api_key
    key, status = self._prompt_api_key()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 253, in _prompt_api_key
    key = apikey.prompt_api_key(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-12-10 10:03:32,683 INFO    MainThread:3555708 [wandb_init.py:_log_setup():533] Logging user logs to /mnt/DGX01/Personal/krusepi/codebase/projects/llms/JAIL-RAG/notebooks/wandb/run-20241210_100332-pjfjknyh/logs/debug.log
2024-12-10 10:03:32,683 INFO    MainThread:3555708 [wandb_init.py:_log_setup():534] Logging internal logs to /mnt/DGX01/Personal/krusepi/codebase/projects/llms/JAIL-RAG/notebooks/wandb/run-20241210_100332-pjfjknyh/logs/debug-internal.log
2024-12-10 10:03:32,710 INFO    MainThread:3555708 [wandb_init.py:_jupyter_setup():479] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f36800f9400>
2024-12-10 10:03:32,710 INFO    MainThread:3555708 [wandb_init.py:init():619] calling init triggers
2024-12-10 10:03:32,710 INFO    MainThread:3555708 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'model_name': 'graph_llm', 'project': 'project_g_retriever', 'seed': 0, 'dataset': 'expla_graphs', 'lr': 1e-05, 'wd': 0.05, 'patience': 2, 'batch_size': 8, 'grad_steps': 2, 'num_epochs': 10, 'warmup_epochs': 1, 'eval_batch_size': 16, 'llm_model_name': '7b', 'llm_model_path': '', 'llm_frozen': 'True', 'llm_num_virtual_tokens': 10, 'output_dir': 'output', 'max_txt_len': 512, 'max_new_tokens': 32, 'max_memory': [80, 80], 'gnn_model_name': 'gt', 'gnn_num_layers': 4, 'gnn_in_dim': 1024, 'gnn_hidden_dim': 1024, 'gnn_num_heads': 4, 'gnn_dropout': 0.0}
2024-12-10 10:03:32,710 INFO    MainThread:3555708 [wandb_init.py:init():669] starting backend
2024-12-10 10:03:32,710 INFO    MainThread:3555708 [wandb_init.py:init():673] sending inform_init request
2024-12-10 10:03:32,711 INFO    MainThread:3555708 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-10 10:03:32,711 INFO    MainThread:3555708 [wandb_init.py:init():686] backend started and connected
2024-12-10 10:03:32,718 INFO    MainThread:3555708 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2024-12-10 10:03:32,719 INFO    MainThread:3555708 [wandb_init.py:init():781] updated telemetry
2024-12-10 10:03:32,774 INFO    MainThread:3555708 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-12-10 10:03:34,795 ERROR   MainThread:3555708 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-10 10:03:34,795 ERROR   MainThread:3555708 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-10 10:03:52,267 INFO    MainThread:3555708 [wandb_settings.py:_apply_login():1989] Applying login settings: {}
2024-12-10 10:03:52,273 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Configure stats pid to 3555708
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Loading settings from /home/pkr/.config/wandb/settings
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Loading settings from /mnt/DGX01/Personal/krusepi/codebase/projects/llms/JAIL-RAG/notebooks/wandb/settings
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-10 10:03:52,291 INFO    MainThread:3555708 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-12-10 10:03:52,291 ERROR   MainThread:3555708 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3555708/1765679085.py", line 3, in <module>
    wandb.init(project=f"{args.project}",
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/analytics/sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 304, in setup
    wandb_login._login(
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 274, in prompt_api_key
    key, status = self._prompt_api_key()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_login.py", line 253, in _prompt_api_key
    key = apikey.prompt_api_key(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-12-10 10:03:52,292 INFO    MainThread:3555708 [wandb_init.py:_log_setup():533] Logging user logs to /mnt/DGX01/Personal/krusepi/codebase/projects/llms/JAIL-RAG/notebooks/wandb/run-20241210_100352-73w9mnn2/logs/debug.log
2024-12-10 10:03:52,292 INFO    MainThread:3555708 [wandb_init.py:_log_setup():534] Logging internal logs to /mnt/DGX01/Personal/krusepi/codebase/projects/llms/JAIL-RAG/notebooks/wandb/run-20241210_100352-73w9mnn2/logs/debug-internal.log
2024-12-10 10:03:52,292 INFO    MainThread:3555708 [wandb_init.py:init():619] calling init triggers
2024-12-10 10:03:52,292 INFO    MainThread:3555708 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'model_name': 'graph_llm', 'project': 'project_g_retriever', 'seed': 0, 'dataset': 'expla_graphs', 'lr': 1e-05, 'wd': 0.05, 'patience': 2, 'batch_size': 8, 'grad_steps': 2, 'num_epochs': 10, 'warmup_epochs': 1, 'eval_batch_size': 16, 'llm_model_name': '7b', 'llm_model_path': '', 'llm_frozen': 'True', 'llm_num_virtual_tokens': 10, 'output_dir': 'output', 'max_txt_len': 512, 'max_new_tokens': 32, 'max_memory': [80, 80], 'gnn_model_name': 'gt', 'gnn_num_layers': 4, 'gnn_in_dim': 1024, 'gnn_hidden_dim': 1024, 'gnn_num_heads': 4, 'gnn_dropout': 0.0}
2024-12-10 10:03:52,292 INFO    MainThread:3555708 [wandb_init.py:init():669] starting backend
2024-12-10 10:03:52,292 INFO    MainThread:3555708 [wandb_init.py:init():673] sending inform_init request
2024-12-10 10:03:52,293 INFO    MainThread:3555708 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-10 10:03:52,293 INFO    MainThread:3555708 [wandb_init.py:init():686] backend started and connected
2024-12-10 10:03:52,298 INFO    MainThread:3555708 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2024-12-10 10:03:52,298 INFO    MainThread:3555708 [wandb_init.py:init():781] updated telemetry
2024-12-10 10:03:52,391 INFO    MainThread:3555708 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-12-10 10:03:52,656 ERROR   MainThread:3555708 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-10 10:03:52,656 ERROR   MainThread:3555708 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/pkr/miniconda3/envs/rag/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
